### ISSUE TITLE
Plugin emits partial css files when building sass.

### ISSUE THREAD

**Issue by dlras2** [jnordberg/wintersmith-sassy#1]
When using partials (sass files with a leading underscore) to modularize sass code, all partials (e.g. `_variables.sass`) are compiled into css files in the build output. This seems to run counter to sass's [guidelines regarding partials](http://sass-lang.com/guide#topic-4).

I am able to prevent the plugin from building these partials by making the render method return no file contents, but I'm not sure if this is the appropriate fix, or if having these files in the rendering tree but not the build output will cause issues.

If there is concern about others' build pipelines, perhaps a `renderPartials` config option or similar?

**Comment by jnordberg** [comment]
Published as 1.1.0 🍻
